force-app/main/default/objects/Mock_Abha__c/Mock_Abha__c.object-meta.xml
<CustomObject>
    <description>Object to store data for mocking ABha API Calls</description>
    <label>Mock Abha</label>
    <nameField>
        <label>Mock Abha Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mock Abha</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mock_Abha__c/fields/AadhaarNumber__c.field-meta.xml
<CustomField>
    <fullName>AadhaarNumber__c</fullName>
    <label>AadhaarNumber</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/ABHA_Address__c.field-meta.xml
<CustomField>
    <fullName>ABHA_Address__c</fullName>
    <label>ABHA Address</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/ABHAid__c.field-meta.xml
<CustomField>
    <fullName>ABHAid__c</fullName>
    <externalId>true</externalId>
    <label>ABHAid</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/dayOfBirth__c.field-meta.xml
<CustomField>
    <fullName>dayOfBirth__c</fullName>
    <label>dayOfBirth</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/districtCode__c.field-meta.xml
<CustomField>
    <fullName>districtCode__c</fullName>
    <label>districtCode</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/districtName__c.field-meta.xml
<CustomField>
    <fullName>districtName__c</fullName>
    <label>districtName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>firstName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/kycVerified__c.field-meta.xml
<CustomField>
    <fullName>kycVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>kycVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>lastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/middleName__c.field-meta.xml
<CustomField>
    <fullName>middleName__c</fullName>
    <label>middleName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/monthOfBirth__c.field-meta.xml
<CustomField>
    <fullName>monthOfBirth__c</fullName>
    <label>monthOfBirth</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/Patient_History__c.field-meta.xml
<CustomField>
    <fullName>Patient_History__c</fullName>
    <label>Patient History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/pincode__c.field-meta.xml
<CustomField>
    <fullName>pincode__c</fullName>
    <label>pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/SimplifiedAbhaID__c.field-meta.xml
<CustomField>
    <fullName>SimplifiedAbhaID__c</fullName>
    <formula>SUBSTITUTE( ABHAid__c , &apos;-&apos;, &apos;&apos;)</formula>
    <label>SimplifiedAbhaID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/stateCode__c.field-meta.xml
<CustomField>
    <fullName>stateCode__c</fullName>
    <label>stateCode</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/stateName__c.field-meta.xml
<CustomField>
    <fullName>stateName__c</fullName>
    <label>stateName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/subdistrictName__c.field-meta.xml
<CustomField>
    <fullName>subdistrictName__c</fullName>
    <label>subdistrictName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/verificationStatus__c.field-meta.xml
<CustomField>
    <fullName>verificationStatus__c</fullName>
    <label>verificationStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VERIFIED</fullName>
            </value>
            <value>
                <fullName>UNVERIFIED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/verificationType__c.field-meta.xml
<CustomField>
    <fullName>verificationType__c</fullName>
    <label>verificationType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AADHAAR</fullName>
            </value>
            <value>
                <fullName>BIOMETRIC</fullName>
            </value>
            <value>
                <fullName>MOBILE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Abha__c/fields/yearOfBirth__c.field-meta.xml
<CustomField>
    <fullName>yearOfBirth__c</fullName>
    <label>yearOfBirth</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AbhaHIUService.cls
@RestResource(urlMapping='/health-information/cm/request')
global with sharing class AbhaHIUService {

     @HttpGet
    global static void getHIUData() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        String queryid = req.params.get('queryid');
        queryid= queryid.replaceAll('[^0-9]', '');
        
        if (String.isBlank(queryid)) {
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(buildErrorResponse('ABDM-1000', 'Missing either Aadhaar or ABHA number.'));
            res.addHeader('Content-Type', 'application/json');
            return;
        }
        
        List<Mock_Abha__c> abhaRecords = [
             select Name,ABHAid__c,ABHA_Address__c,AadhaarNumber__c,address__c,
            dayOfBirth__c,yearOfBirth__c,monthOfBirth__c,mobile__c,districtCode__c,
            districtName__c,firstName__c,middleName__c,lastName__c,gender__c,
            status__c,stateName__c,subdistrictName__c,kycVerified__c,
            verificationStatus__c,verificationType__c,pincode__c,
            CreatedDate,stateCode__c,Patient_History__c from Mock_Abha__c 
            where  (AadhaarNumber__c = :queryid or SimplifiedAbhaID__c = :queryid) LIMIT 1
        ];
    	
        if (abhaRecords.isEmpty()) {
            res.statusCode = 404;
            res.responseBody = Blob.valueOf(buildErrorResponse('ABDM-1030', 'Record not found'));
            res.addHeader('Content-Type', 'application/json');
            return;
        }

        Mock_Abha__c record = abhaRecords[0];
        if (record.Patient_History__c == null || record.Patient_History__c.trim() == '') {
            res.statusCode = 404;
            res.responseBody = Blob.valueOf(buildErrorResponse('ABDM-1031', 'No HIU data available'));
            res.addHeader('Content-Type', 'application/json');
            return;
        }
        Map<String, Object> responseBody = new Map<String, Object>{
            'ABHANumber' => record.ABHAid__c,
            'AadhaarNumber' => record.AadhaarNumber__c,
            'preferredAbhaAddress' => record.ABHA_Address__c,
            'mobile' => maskMobile(record.mobile__c),
            'firstName' => record.firstName__c,
            'middleName' => record.middleName__c,
            'lastName' => record.lastName__c,
            'name' => record.Name,
            'yearOfBirth' => String.valueOf(record.yearOfBirth__c),
            'dayOfBirth' => String.valueOf(record.dayOfBirth__c),
            'monthOfBirth' => String.valueOf(record.monthOfBirth__c),
            'gender' => record.gender__c,
            'profilePhoto' => '',
            'status' => record.status__c,
            'stateCode' => String.valueOf(record.stateCode__c),
            'districtCode' => String.valueOf(record.districtCode__c),
            'pincode' => record.pincode__c,
            'address' => record.address__c,
            'kycPhoto' => '',
            'kycVerified' => record.kycVerified__c,
            'verificationStatus' => record.verificationStatus__c,
            'verificationType' => record.verificationType__c,
            'stateName' => record.stateName__c,
            'districtName' => record.districtName__c,
            'subdistrictName' => record.subdistrictName__c,
            'authMethods' => new List<String>{'MOBILE_OTP','AADHAAR_BIO','AADHAAR_OTP','DEMOGRAPHICS','PASSWORD'},
            'tags' => new Map<String, String>(),
            'createdDate' => record.CreatedDate.format('dd-MM-yyyy'),
            'PatientHistory' => record.Patient_History__c
        };
        res.statusCode = 200;
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody));
        res.addHeader('Content-Type', 'application/json');
    }
    private static String maskMobile(String mobile) {
        if (String.isBlank(mobile) || mobile.length() < 10) return mobile;
        return '******' + mobile.right(4);
    }
    private static String buildErrorResponse(String code, String message) {
        Map<String, Object> errorBody = new Map<String, Object>{
            'error' => new Map<String, String>{
                'code' => code + ': ',
                    'message' => message
                    }
        };
        return JSON.serialize(errorBody);
    }
}